<?php
$ltrstr['Change Subscription']    = 'Unsubscribe'; 
$ltrstr['Change Notification']    = 'Change Notification'; 
$ltrstr['Subscribe']              = 'Subscribe'; 

$ltrstr['CHANGE SUBSCRIPTION']    = 'UNSUBSCRIBE'; 
$ltrstr['SUBSCRIBE']              = 'SUBSCRIBE'; 

$ltrstr['Go to the Creators page'] = 'Go to the Creators page';
$ltrstr['Go to my Mypage']         = 'Go to my Mypage';

$ltrstr['Go back to linktrail']   = 'Go back to the directory';
$ltrstr['Recommend this trail']   = 'Recommend this trail';
$ltrstr['Add a link']             = 'Add a link';
$ltrstr['Change Permissions']     = 'Set Permissions';

$ltrstr['Create this Trail']      = '&nbsp;Create this trail&nbsp;&nbsp';
$ltrstr['Login failed']      	  = 'Your username or password did not match. Please try again.<p><table border=0><tr valign="top"><td><font face="Verdana, Arial, Helvetica, sans-serif" size=2>&#8226;</font></td><td><font face="Verdana, Arial, Helvetica, sans-serif" size=2>Not a member yet? <a href="/Experts/New_User">Sign up here!</a></font></td></tr><tr valign="top"><td><font face="Verdana, Arial, Helvetica, sans-serif" size=2>&#8226;</font></td><td><font face="Verdana, Arial, Helvetica, sans-serif" size=2><a href="/Experts/Forgotten_Password?dologout=1">Forgot your username or password?</a></font></td></tr></table><p>';
$ltrstr['Error']      			  = 'Oops ';

$ltrstr['Trail_Login'] 			  = 'Please log in to create a new trail.';
$ltrstr['LOGIN'] 			      = 'LOGIN';
$ltrstr['Login'] 			      = 'Login';
$ltrstr['Logout'] 			      = 'Logout';
$ltrstr['Trail_Login_Add'] 	      = 'To add a Link, please log in.';
$ltrstr['Trail_Login_Sub'] 	      = 'To subscribe to this trail, please log in.';
$ltrstr['Trail_Login_Req'] 	      = 'Please enter your username and password.';

$ltrstr['Edit Permissions']		  = 'SET PERMISSIONS';
$ltrstr["Share this trail"]		  = "Recommend this trail";

$ltrstr['Profile']				  = "Change profile";
$ltrstr['Security Preferences']	  = "Change password";
$ltrstr['Preferences']	  		  = "Customize linktrail";
$ltrstr['Settings']	  		      = "Settings";
$ltrstr['SETTINGS']	  		      = "SETTINGS";
$ltrstr['MESSAGES']	  		      = "MESSAGES";
$ltrstr['Inbox']	  		      = "Received messages";
$ltrstr['Outbox']	  		      = "Sent messages";
$ltrstr['Composer']	  		      = "Compose a message";


$ltrstr['Pass_Nomatch']			  = "Your passwords did not match.";
$ltrstr['Passnote']				  = "";
$ltrstr['User Exists']			  = "This name is already in use by another member. Please select a username from the list below or try another one.";
$ltrstr['No Username Provided']   = "You forgot to provide a user name";
$ltrstr['No Email Provided']      = "You forgot to provide an Email address or the address you provided is not valid.";

$ltrstr['gender_m']				  = "Male";
$ltrstr['gender_f']				  = "Female";
$ltrstr['gender_o']				  = "Other";

$ltrstr['Overview']               = 'Overview';
$ltrstr['Company History']        = 'Company history';
$ltrstr['Our Team']               = 'Team';
$ltrstr['Our Philosophy']         = 'Philosophy';
$ltrstr['Careers']                = 'Jobs';
$ltrstr['Contact Us']             = 'Contact';
$ltrstr['Press Releases']         = 'Press releases';
$ltrstr['In the News']            = 'In the news';
$ltrstr['FAQ']                    = 'FAQ';
$ltrstr['Official Logos']         = 'Official logos';
$ltrstr['Why Advertise']          = 'Why advertise?';
$ltrstr['Audience']               = 'Audience';
$ltrstr['Ad Oportunities']        = 'Ad opportunities';

$ltrstr['Database Error']         = 'A database error has occured. Please <a href="#report" target="_self">report this</a> to the webmaster.';
$ltrstr['Error_Report_Sent']      = '&nbsp;<p><font face="Verdana, Arial, Helvetica, sans-serif" size=2>Your report has been sent to the webmaster. We will get in touch with you as soon as the problem is fixed. Thank you.<p><a href="/" target="ltrmain233">Go Back to linktrail</a></font>';

$ltrstr['Share This Trail']       = 'RECOMMEND THIS TRAIL';
$ltrstr['Updated']                = 'Updated';
$ltrstr['New']                    = 'New';

$ltrstr['Go to']                  = 'Go to';
$ltrstr['directory']              = 'directory';
$ltrstr['Creator']                = 'creator';
$ltrstr['mypage']                 = 'mypage';

$ltrstr['Add a link button']      = "&nbsp;Add this link&nbsp;";
$ltrstr['Go Back']                = '<p><font size="1" face="verdana, arial, helvetica">go back without saving changes</font>';

$ltrstr['Form Error']             = '<p><font size="2" face="verdana, arial, helvetica"><b><font color="ff0000">Error:</font></b> The information you supplied in the field(s) marked with <font color="ff0000">*</font> is incorrect. Please check and submit this form again. Thank you.</font>';
$ltrstr['Form Error Mark']        = '<font size="2" face="verdana, arial, helvetica" color="#ff0000">*</font>';
$ltrstr['This slot']              = '&lt;&lt;&lt;&nbsp;&nbsp;&nbsp; This Slot &nbsp;&nbsp;&nbsp;&gt;&gt;&gt;';
$ltrstr['next']                   = "Next";
$ltrstr['prev']                   = "Previous";

$ltrstr["Search_Error"]['1004']   = "Your query contained a caracter the server could not recognize.";
$ltrstr["Search_Error"]['1005']   = '<font size="2" face="verdana, arial, helvetica"><b><font color="ff0000">Error:</font></b> Quotation marks are not balanced in your query.';
$ltrstr["Search_Error"]['1007']   = "Your query is too long.";
$ltrstr["Search_Error"]['1008']   = "The server could not understand your query because some boolean operators have been placed incorrectly.";
$ltrstr["Search_Error"]['2003']   = "The server could not understand your query because some boolean operators have been placed incorrectly.";
$ltrstr["Search_Error"]['2004']   = 'You have used "(" without ")" or ")" without "("';
$ltrstr["Search_Error"]['unknown']= 'An unknown error has occured while processing your query. Please try again or contact our <ahref="mailto:support@linktrail.com">support</a>';

$ltrstr['Privacy']                = "Privacy statement";
$ltrstr['Terms of service']       = "Terms of service";
$ltrstr['Report Bug']             = "Report a bug";
$ltrstr['Tour']                   = "Take a tour";
$ltrstr['No User Desc']           = "This user did not enter his or her description yet.";

$ltrstr['Languages Short'][1]     = '[en]';
$ltrstr['Languages Short'][2]     = '[de]';

$ltrstr['Bad language']           = 'Bad language';

$ltrstr['What is linktrail']      = "What is linktrail?";
$ltrstr['What is a trail']        = "What is a trail?";
$ltrstr['Add your best links']    = "Add your best links.";
$ltrstr['Find a person']          = "Find a real person<br>behind every trail.";
$ltrstr['Contact any member']     = "Contact any member of linktrail.";
$ltrstr['Make friendship']        = "Make friendships.";
$ltrstr['Subscribe a trail']      = "Subscribe to trails.";
$ltrstr['Create a trail']         = "Create your own trails.";
$ltrstr['Set permissions']        = "Set permissions.";
$ltrstr['Register now']           = "Register now!";

$ltrstr['Edit this link']         = "edit";
$ltrstr['Find related']           = "find related trails";
$ltrstr['Send Message']           = "SEND MESSAGE";
$ltrstr['Go Back Message']        = "Go back without sending the message";
$ltrstr['Contact the author']     = "Contact %s";
$ltrstr['Subject missing']        = "<p>Please enter at least the subject of the message";
$ltrstr['Message_Text_1001']      = "has been deleted";
$ltrstr['Message_Text_1002']      = "has been moved";
$ltrstr['Message_Text_1003']      = "has been changed";

$ltrstr['Message_FE_start']       = 'has elected you as a featured expert in <a href="%s">%s</a>';
$ltrstr['Message_FE_end']         = 'has revoked your status as a featured expert in <a href="%s">%s</a>';
$ltrstr['Message_slot_start']     = 'has chosen to feature your trail <a href="%s" target="%s" onClick="openIt(\'%s\');">%s</a> in <a href="%s">%s</a>';
$ltrstr['Message_slot_end']       = 'has removed your trail <a href="%s" target="%s" onClick="openIt(\'%s\');">%s</a> from being featured in <a href="%s">%s</a>';

$ltrstr['Errors occurred']        = 'The following error(s) occurred:';
$ltrstr['User not found']         = "The selected user could not be found in the database";
$ltrstr['Message sent']           = "Your message has successfully been sent";

$ltrstr['User_Action_1004']       = "added";
$ltrstr['User_Action_1005']       = "moved";
$ltrstr['User_Action_1006']       = "changed";
$ltrstr['User_Action_1007']       = "deleted";

$ltrstr['Message sent in trail']  = 'This message has been sent from the trail <a href="%s" target="%s" onClick="openIt(\'%s\');">%s</a>';

$ltrstr['subscribe_link']         = '<a href="%s">subscribe</a>';
$ltrstr['decline_link']           = '<a href="%s">reject</a>';
$ltrstr['delete_link']            = '<a href="%s">delete</a>';
$ltrstr['close_link']             = '<a href="%s">close</a>';
$ltrstr['read_link']              = '<a href="%s">read</a>';
$ltrstr['acceptnote']             = '<i>Click <a href="%s">subscribe</a> to accept this recommendation and to list this trail on your Mypage.</i>';
$ltrstr['acceptednote']           = '<i>You have accepted this recommendation and subscribed this trail.</i>';
$ltrstr['declinednote']           = '<i>You have rejected this recommendation.</i>';

$ltrstr['recommends']             = "recommends";
$ltrstr['recommended']            = "recommended";

$ltrstr['terminated friendship']  = "has quit his friendship with you";
$ltrstr['ignored friendship']     = "has rejected your friendship request";
$ltrstr['accepted friendship']    = "has accepted your friendship request";
$ltrstr['canceled friendship']    = "has canceled his friendship request to you";

$ltrstr['trail subscribed']       = "has subscribed your trail %s";
$ltrstr['trail unsubscribed']     = "has unsubscribed your tral %s";
$ltrstr['recommendation declined']= "has decliend your recommendation of %s";
$ltrstr['recommendation accepted']= "has accepted your recommendation of %s";

$ltrstr['common link to trail']   = '<a href="%s" target="%s" onClick="openIt(\'%s\');">%s</a>';

$ltrstr['accepted self']          = 'you have accepted the friendship request of <a href="%s">%s</a>';
$ltrstr['terminated self']        = 'you have terminated the friendship with <a href="%s">%s</a>';
$ltrstr['ignored self']           = 'you have ignored the friendship request of <a href="%s">%s</a>';
$ltrstr['canceled self']          = 'you have canceled your friendship request to <a href="%s">%s</a>';

$ltrstr['trail_link']             = '<a href="%s" target="%s" onClick="openIt(\'%s\');">%s</a>';
$ltrstr['Back without logging in']= 'go back without logging in';
$ltrstr['Back without recommend'] = 'go back without recommendation';
$ltrstr['Back without perms']     = 'go back without setting permissions';
$ltrstr['Back without unsub']     = 'go back without unsubscribing';
$ltrstr['Back without sub']       = 'go back without subscribing';

$ltrstr['Trail title']            = 'trail title';
$ltrstr['Trail description']      = 'trail description';
$ltrstr['Edit Trail title']       = 'Edit trail title';
$ltrstr['Edit Trail description'] = 'Edit trail description';

$ltrstr['Add Trail title']        = 'Enter a title for this trail:';
$ltrstr['Add Trail description']  = 'What is this trail all about?';
$ltrstr['Admin Trail del']        = 'We are sorry to inform you that linktrail has removed your trail, because it violated the terms of service you accepted when registering.<p>If you have further questions, feel free to ask our <a href="mailto:support@linktrail.com">support staff</a>';

$ltrstr['In Reply to']            = "<p><b>In Reply to</b>:<br> <i>%s</i>";
$ltrstr['Displaying messages']    = "Displaying %s message(s).";
$ltrstr['lms comfirmation'][1]    = "Your reply has been sent.";
$ltrstr['lms comfirmation'][2]    = "Message deleted.";
$ltrstr['lms comfirmation'][3]    = "The friendship request has been accepted.";
$ltrstr['lms comfirmation'][4]    = "The friendship request has been declined.";
$ltrstr['lms comfirmation'][5]    = "The recommendation has been accepted. Trail subscribed.";
$ltrstr['lms comfirmation'][6]    = "The recommendation has been declined.";

$ltrstr['inbox']                  = "received messages";
$ltrstr['outbox']                 = "sent messages";

$ltrstr['create a new trail']     = "Create a new trail";
$ltrstr['make a friendship']      = "Request friendship";
$ltrstr['accept request']         = "Accept the friendship request of %s";
$ltrstr['cancel friendship']      = "Quit friendship";
$ltrstr['editmode']               = "Edit this node (admin)";
$ltrstr['iw_login']               = "Login";
$ltrstr['iw_logout']              = "Logout (%s)";
$ltrstr['iw_register']            = "Register";
$ltrstr['iw_linkdrop']            = "Paste shortcut to %s here";
$ltrstr['iw_nodedrop']            = "Paste category %s here";
$ltrstr['iw_traildrop']           = "Paste trail %s here";
$ltrstr['iw_readmsgs']            = 'Messagecenter';
$ltrstr['iw_readmsgs_sub']        = '<br>%d new message(s)';
$ltrstr['Home']                   = 'Home';
$ltrstr['Mypage']                 = 'Mypage';
$ltrstr['comfirm_friendship']     = 'Accept friendship request of %s';
$ltrstr['quit_friendship']        = 'Quit my friendship with %s';
$ltrstr['make_friendship']        = 'Request a friendship with %s';
//$ltrstr['Settings']	  		      = "Settings";

?>